---
# SPDX-FileCopyrightText: (c) 2016-2019, 2021 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileType: SOURCE

image: "openjdk:17-jdk-alpine"

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
    - cache/
    - .gradle/caches/
    - .gradle/notifications/
    - .gradle/wrapper/

variables:
  GIT_DEPTH: "1"
  # SAST_EXPERIMENTAL_FEATURES: "true"

before_script:
  - export UPLOAD_BUILD_SCAN="true"
  - export FAST_BUILD="true"
  - export GRADLE_USER_HOME="$PWD/.gradle"
  - apk add bash zip~=3.0

include:
  # - template: Security/Dependency-Scanning.gitlab-ci.yml
  # - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  # - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test
  # - execute
  # - package

build:
  stage: build
  script: "./gradlew buildOtaOSS"
  artifacts:
    paths:
      - output/*.zip*
    expire_in: 1 week
  only:
    - main

# license_scanning:
#   stage: test
#   artifacts:
#     paths:
#       - gl-license-scanning-report.json

sast:
  stage: test
  artifacts:
    paths:
      - gl-sast-report.json

after_script:
  - rm -f  "$GRADLE_USER_HOME/caches/modules-2/modules-2.lock"
  - rm -fr "$GRADLE_USER_HOME/caches/*/plugin-resolution/"
