---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

image: "eclipse-temurin:17-jdk-alpine"

variables:
  GIT_DEPTH: "1"

# Cache expiration: 14 days
cache:
  key: "build-cache"
  paths:
    - cache/
  when: "always"

before_script: |
  # Install dependencies
  apk add bash zip~=3.0 wget || exit "${?}"

include:
  # - template: Security/Dependency-Scanning.gitlab-ci.yml
  # - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  # - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test

job-build-oss:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG != "nightly"
  cache: []
  script: "BUILD_TYPE='oss' './build.sh'"

job-build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script: "BUILD_TYPE='full' './build.sh'"
  artifacts:
    paths:
      - output/*.zip*
    expire_in: 1 hour

# license_scanning:
#   stage: test
#   artifacts:
#     paths:
#       - gl-license-scanning-report.json

sast:
  stage: test
  cache: []
  before_script: []
