---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

image: "eclipse-temurin:17-jdk-alpine"

variables:
  GIT_DEPTH: "1"
  FAST_BUILD: "true"

# Cache expiration: 14 days
cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
    prefix: "$CI_JOB_NAME"
  paths:
    - cache/
    - .gradle/caches/
    - .gradle/notifications/
    - .gradle/wrapper/
  when: "always"

before_script:
  - export GRADLE_USER_HOME="${PWD:?}/.gradle"
  - apk add bash grep wget zip~=3.0

include:
  # - template: Security/Dependency-Scanning.gitlab-ci.yml
  # - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  # - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test

build-ota-oss:
  stage: build
  script: "./gradlew buildOtaOSS"
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
    #   - output/*.zip*
    expire_in: 1 day

build-ota:
  stage: build
  script: "./gradlew buildOta"
  only:
    - main

# license_scanning:
#   stage: test
#   artifacts:
#     paths:
#       - gl-license-scanning-report.json

sast:
  stage: test
  artifacts:
    paths:
      - gl-sast-report.json
    expire_in: 1 day

after_script:
  - rm -f  "$GRADLE_USER_HOME/caches/modules-2/modules-2.lock"
  - rm -fr "$GRADLE_USER_HOME/caches/*/plugin-resolution/"
