---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: "Utils tester"
permissions: {}
on:
  push:
    paths:
      - ".github/workflows/utils-tester.yml"
      - "utils/**"
  pull_request:
    paths:
      - ".github/workflows/utils-tester.yml"
      - "utils/**"
  workflow_dispatch:

jobs:
  deviceinfo:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "DeviceInfo (${{ matrix.os }})"
    runs-on: "${{ matrix.os }}"
    timeout-minutes: 20

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v6
      - name: "Test script on Bash"
        shell: bash
        timeout-minutes: 10
        run: |
          # Testing script...
          bash --version | head -n 1
          printf '\n'
          bash '${{ github.workspace }}/utils/device-info.sh' --version
          printf '\n'
          bash '${{ github.workspace }}/utils/device-info.sh' -- '${{ github.workspace }}/utils/test-files/Getprop-EMU-Pixel 4 API 33.txt'
